name: Build snapshot version and upload to Maven Central

on:
  push:
    branches: [ "main" ]

jobs:
    call-snapshot-job:
      uses: project-ncl/shared-github-actions/.github/workflows/maven-snapshot.yml@main
      with:
        project_name: 'project-ncl/kafka-store'
        quarkus_jib_image: true
      secrets: inherit
